import { Principal } from "@dfinity/principal";
import Head from "next/head";
import { useEffect, useState } from "react";
import { canisterId, createActor } from "../../declarations/Axon";
import { Result_2 } from "../../declarations/Axon/Axon.did";

const Axon = createActor(canisterId, {
  agentOptions: { host: "https://ic0.app" },
});

export default function Home() {
  const [neurons, setNeurons] = useState<bigint[]>(null);
  const [operators, setOperators] = useState<Principal[]>(null);
  const [activeProposals, setActiveProposals] = useState<Result_2>(null);
  const fetchData = async () => {
    if (!canisterId) return;

    setOperators(await Axon.getOperators());
    setNeurons(await Axon.getNeuronIds());
    setActiveProposals(await Axon.getActiveProposals());
  };

  useEffect(() => {
    fetchData();
  }, []);

  return (
    <div className="flex flex-col items-center bg-gradient-to-b from-yellow-300 via-red-400 to-pink-500">
      <div className="flex flex-col justify-between min-h-screen w-full sm:max-w-screen-lg p-4">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="flex flex-col gap-8">
          <div className="flex justify-center py-4">
            <h1 className="text-5xl font-bold filter drop-shadow-md">Axon</h1>
          </div>
          <section className="p-4 bg-gray-50 rounded-lg shadow-lg">
            <h2 className="text-xl font-bold">Canister</h2>
            {canisterId ? (
              <a
                className="underline"
                target="_blank"
                rel="noopener noreferrer"
                href={`https://ic.rocks/principal/${canisterId}`}
              >
                {canisterId}
              </a>
            ) : (
              "Not found"
            )}
          </section>

          <section className="p-4 bg-gray-50 rounded-lg shadow-lg">
            <h2 className="text-xl font-bold">Operators</h2>
            {operators ? (
              <ul>
                {operators.map((p) => (
                  <li key={p.toText()}>{p.toText()}</li>
                ))}
              </ul>
            ) : (
              "Loading..."
            )}
          </section>

          <section className="p-4 bg-gray-50 rounded-lg shadow-lg">
            <h2 className="text-xl font-bold">Neurons</h2>
            {neurons ? (
              neurons.length > 0 ? (
                <ul>
                  {neurons.map((n) => (
                    <li key={n.toString()}>{n.toString()}</li>
                  ))}
                </ul>
              ) : (
                "None"
              )
            ) : (
              "Loading..."
            )}
          </section>

          <section className="p-4 bg-gray-50 rounded-lg shadow-lg">
            <h2 className="text-xl font-bold">Active Proposals</h2>
            {activeProposals ? (
              "ok" in activeProposals ? (
                activeProposals.ok.length > 0 ? (
                  <ul>
                    {activeProposals.ok.map((p) => (
                      <li key={p.id.toString()}>p.id</li>
                    ))}
                  </ul>
                ) : (
                  "None"
                )
              ) : (
                JSON.stringify(activeProposals.err)
              )
            ) : (
              "Loading..."
            )}
          </section>
        </main>

        <footer>
          <a
            href="https://github.com/FloorLamp/axon"
            className="underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            View on Github
          </a>
        </footer>
      </div>
    </div>
  );
}
